/** Single source of English UI copy */
export const copy = {
  appTitle: 'Goroutine',
  login: 'Log in',
  register: 'Create account',
  email: 'Email',
  password: 'Password',
  alreadyHaveAccount: 'Already have an account?',
  notSignedUp: 'Not signed up?',
  logout: 'Log out',
  boards: 'Boards',
  boardListTitle: 'Your boards',
  createBoard: 'Create board',
  createBoardTitle: 'Create board',
  nameRequired: 'Name is required',
  createColumnTitle: 'New column',
  createTaskTitle: 'New task',
  newBoardName: 'New board',
  newBoardDescription: 'Add a short description',
  populateBoard: 'Stress populate',
  populateBoardBlurb: '50 columns, 15–30 random tasks each (lorem ipsum text).',
  examplePopulateBoard: 'Example populate',
  examplePopulateBlurb: 'Sprint 42 demo board shipped as example_board.json.',
  populateCinemaBanner: 'Populating…',
  importBoardBanner: 'Importing board…',
  copyBoardJson: 'Copy JSON',
  pasteBoardJson: 'Paste JSON',
  copyBoardTitle: 'Copy board JSON',
  copyBoardPick: 'Board',
  clipboardAccessDenied: 'Clipboard access was denied.',
  importBoardInvalid: 'Invalid or unsupported JSON.',
  editBoard: 'Edit board',
  deleteBoard: 'Delete board',
  deleteBoardConfirm: 'Delete this board? This cannot be undone.',
  cancel: 'Cancel',
  save: 'Save',
  delete: 'Delete',
  openBoard: 'Open board',
  loadingBoards: 'Loading boards',
  loadingBoard: 'Loading board',
  emptyBoards: 'No boards yet. Create one below.',
  somethingWrong: 'Something went wrong',
  /** Server 5xx — never show raw technical messages from the API body. */
  errorServer: 'Something went wrong on our side. Please try again in a moment.',
  errorUnauthorized: 'Please sign in again.',
  errorNotFound: 'We could not find what you asked for.',
  errorBoardNotFound: 'This board does not exist or you no longer have access.',
  errorColumnNotFound: 'This column could not be found. Try refreshing the page.',
  errorTaskNotFound: 'This task could not be found. Try refreshing the page.',
  errorUserExists: 'An account with this email already exists. Try signing in.',
  errorInvalidCredentials: 'Incorrect email or password.',
  errorValidationIntro: 'Please fix the following:',
  registerSuccess: 'Account created. You can log in now.',
  serverStateSynced: 'In sync',
  serverStatePending: 'Saving…',
  noDescription: 'No description',
  boardName: 'Board name',
  boardDescription: 'Description',
  columnName: 'Column name',
  columnDescription: 'Column description',
  taskName: 'Task name',
  taskDescription: 'Task description',
  addColumn: 'Add column',
  addTask: 'Add task',
  editColumn: 'Edit column',
  editTask: 'Edit task',
  deleteColumn: 'Delete column',
  deleteTask: 'Delete task',
  deleteColumnConfirm: 'Delete this column and all tasks inside?',
  deleteTaskConfirm: 'Delete this task?',
  newColumnName: 'New column',
  newColumnDescription: 'Column description',
  newTaskName: 'New task',
  newTaskDescription: 'Task description',
  canvasPanHint: 'Drag empty space or hold Ctrl and drag to pan. Scroll to zoom.',
  boardDetailPanHint: 'Arrows or ctrl+drag to move, wheel to zoom, double click to edit.',
  routeLoading: 'Loading…',
  loginAsTestUser: 'Login as test user',
  taskCreated: 'Created',
  taskUpdated: 'Updated',
  boardCreated: 'Created',
  boardUpdated: 'Updated',
  validationNameRequired: 'Name cannot be empty.',
  validationNameTooLong: 'Name must be at most 128 characters.',
  validationDescriptionTooLong: 'Description must be at most 1024 characters.',
  validationPasswordTooShort: 'Password must be at least 6 characters.',
  validationEmailRequired: 'Enter your email address.',
  validationEmailInvalid: 'Invalid email address.',
  clientValidationBypass: 'Bypass client validation',
} as const

/** Compact board summary for header / list (English plural rules). */
export function formatBoardCompactStats(columns: number, tasks: number): string {
  const cUnit = columns === 1 ? 'column' : 'columns'
  const tUnit = tasks === 1 ? 'task' : 'tasks'
  return `${columns} ${cUnit} · ${tasks} ${tUnit}`
}

export function formatTaskColumnCount(count: number): string {
  return `${count} ${count === 1 ? 'task' : 'tasks'}`
}
